# Generated by Django 5.2 on 2025-05-06 00:52

import django.db.models.deletion
import prophet.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Fixture',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Gambler',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('email_address', models.EmailField(help_text='Please Enter Lecturer Email Address', max_length=200)),
                ('username', models.EmailField(help_text='Enter a valid Username', max_length=200, unique=True)),
                ('first_name', models.CharField(help_text='Please Enter Student First Name', max_length=200)),
                ('last_name', models.CharField(help_text='Please Enter Student Last Name', max_length=200)),
                ('phone_number', models.CharField(help_text='Enter phone number in the format 0798073204 or +254798073404', max_length=13, validators=[prophet.validators.validate_kenyan_phone_number])),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('player_code', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('position', models.CharField(choices=[('GK', 'Goalkeeper'), ('CB', 'Central Defence'), ('WB', 'Wing Defence'), ('DM', 'Defensive Midfield'), ('AM', 'Attacking Midfield'), ('WG', 'Winger'), ('ST', 'Striker')], max_length=20)),
                ('effect', models.CharField(choices=[('threat', 'Threat'), ('best', 'Best'), ('moderate', 'Moderate'), ('required', 'Required')], max_length=20)),
                ('rating', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='PredictionType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(choices=[('1X2', '1X2'), ('GG', 'GG'), ('Over', 'Over'), ('Under', 'Under'), ('Handicap', 'Handicap'), ('Correct Score', 'Correct Score')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='System_User',
            fields=[
                ('username', models.CharField(help_text='Enter a valid Username', max_length=50, primary_key=True, serialize=False, unique=True)),
                ('password_hash', models.CharField(help_text='Enter a valid password', max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='HeadToHead',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('match_date', models.DateField()),
                ('result', models.CharField(max_length=50)),
                ('fixture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='head_to_heads', to='prophet.fixture')),
            ],
        ),
        migrations.CreateModel(
            name='League',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leagues', to='prophet.country')),
            ],
        ),
        migrations.AddField(
            model_name='fixture',
            name='league',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fixtures', to='prophet.league'),
        ),
        migrations.CreateModel(
            name='InjuredPlayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='injury', to='prophet.player')),
            ],
        ),
        migrations.CreateModel(
            name='Prediction',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('value', models.CharField(max_length=100)),
                ('prediction_site', models.CharField(max_length=100)),
                ('site_accuracy', models.DecimalField(decimal_places=2, max_digits=5)),
                ('team_effort', models.CharField(choices=[('none', 'No Motivation'), ('survival', 'Fighting Relegation'), ('promotion', 'Fighting Promotion'), ('title', 'Fighting for Title'), ('qualification', 'Fighting for Qualification'), ('rivalry', 'Playing Rivalry Game')], default='none', max_length=20)),
                ('fixture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predictions', to='prophet.fixture')),
                ('prediction_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prophet.predictiontype')),
            ],
        ),
        migrations.CreateModel(
            name='SuspendedPlayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='suspension', to='prophet.player')),
            ],
        ),
        migrations.CreateModel(
            name='PasswordResetToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prophet.system_user')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='prophet.league')),
            ],
        ),
        migrations.CreateModel(
            name='PredictedResult',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('predicted_result', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('fixture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predicted_results', to='prophet.fixture')),
                ('prediction_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prophet.predictiontype')),
                ('away_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='away_predictions', to='prophet.team')),
                ('home_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_predictions', to='prophet.team')),
            ],
        ),
        migrations.AddField(
            model_name='player',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='prophet.team'),
        ),
        migrations.AddField(
            model_name='fixture',
            name='away_team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='away_fixtures', to='prophet.team'),
        ),
        migrations.AddField(
            model_name='fixture',
            name='home_team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_fixtures', to='prophet.team'),
        ),
        migrations.CreateModel(
            name='TeamForm',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('game_number', models.PositiveIntegerField()),
                ('result', models.CharField(choices=[('W', 'Win'), ('D', 'Draw'), ('L', 'Loss')], max_length=1)),
                ('over_under', models.CharField(choices=[('Over', 'Over'), ('Under', 'Under')], max_length=5)),
                ('gg', models.CharField(choices=[('gg', 'GG'), ('no gg', 'No GG')], max_length=5)),
                ('fixture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forms', to='prophet.fixture')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forms', to='prophet.team')),
            ],
        ),
        migrations.CreateModel(
            name='TeamStat',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fixture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_stats', to='prophet.fixture')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prophet.team')),
            ],
        ),
    ]
